-- MySQL Script generated by MySQL Workbench
-- Fri Apr 14 02:01:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lasimethris02
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lasimethris02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lasimethris02` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

-- -----------------------------------------------------
-- Table `lasimethris02`.`verifikasi_v2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasimethris02`.`verifikasi_v2` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `verificator_id` INT NULL,
  `commitmentbackdate_id` BIGINT NOT NULL,
  `no_pengajuan` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `notes` TEXT NULL,
  `status` ENUM('submitted', 'pending', 'approved', 'rejected') NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `verif_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lasimethris02`.`commitment_backdates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasimethris02`.`commitment_backdates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `npwp` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `no_ijin` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `periodetahun` INT NULL DEFAULT NULL,
  `tgl_ijin` DATE NULL DEFAULT NULL,
  `tgl_end` DATE NULL DEFAULT NULL,
  `no_hs` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `volume_riph` DOUBLE(8,2) NULL DEFAULT NULL,
  `stok_mandiri` DOUBLE NULL DEFAULT NULL,
  `organik` DOUBLE NULL DEFAULT NULL,
  `npk` DOUBLE NULL DEFAULT NULL,
  `dolomit` DOUBLE NULL DEFAULT NULL,
  `za` DOUBLE NULL DEFAULT NULL,
  `mulsa` DOUBLE NULL DEFAULT NULL,
  `poktan_share` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `importir_share` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `status` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formRiph` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formSptjm` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `logbook` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formRt` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formRta` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formRpo` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `formLa` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `skl` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `verifikasi_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `commitment_backdates_no_ijin_unique` (`no_ijin` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `verifikasi_id_idx` (`verifikasi_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `lasimethris02`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verifikasi_id`
    FOREIGN KEY (`verifikasi_id`)
    REFERENCES `lasimethris02`.`verifikasi_v2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3;

USE `lasimethris02` ;

-- -----------------------------------------------------
-- Table `lasimethris02`.`pks_mitras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasimethris02`.`pks_mitras` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `commitmentbackdate_id` BIGINT UNSIGNED NOT NULL,
  `master_kelompok_id` BIGINT NULL DEFAULT NULL,
  `no_ijin` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `no_perjanjian` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `tgl_perjanjian_start` DATE NULL DEFAULT NULL,
  `tgl_perjanjian_end` DATE NULL DEFAULT NULL,
  `jumlah_anggota` INT NULL DEFAULT NULL,
  `luas_rencana` INT NULL DEFAULT NULL,
  `varietas_tanam` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `periode_tanam` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `provinsi_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `kabupaten_id` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `kecamatan_id` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `kelurahan_id` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `berkas_pks` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pks_mitras_commitmentbackdate_id_foreign` (`commitmentbackdate_id` ASC) VISIBLE,
  CONSTRAINT `pks_mitras_commitmentbackdate_id_foreign`
    FOREIGN KEY (`commitmentbackdate_id`)
    REFERENCES `lasimethris02`.`commitment_backdates` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `lasimethris02`.`anggota_mitras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lasimethris02`.`anggota_mitras` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pks_mitra_id` BIGINT UNSIGNED NOT NULL,
  `commitmentbackdate_id` BIGINT UNSIGNED NOT NULL,
  `no_ijin` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `master_anggota_id` BIGINT UNSIGNED NOT NULL,
  `nama_lokasi` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `latitude` TEXT COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `longitude` TEXT COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `altitude` DOUBLE NULL DEFAULT NULL,
  `luas_kira` DECIMAL(10,2) NULL DEFAULT NULL,
  `polygon` TEXT CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tgl_tanam` DATE NULL DEFAULT NULL,
  `luas_tanam` FLOAT NULL DEFAULT NULL,
  `varietas` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `tgl_panen` DATE NULL DEFAULT NULL,
  `volume` DOUBLE NULL DEFAULT NULL,
  `tanam_doc` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `tanam_pict` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `panen_doc` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `panen_pict` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `anggota_mitras_commitmentbackdate_id_foreign` (`commitmentbackdate_id` ASC) VISIBLE,
  INDEX `anggota_mitras_no_ijin_foreign` (`no_ijin` ASC) VISIBLE,
  INDEX `anggota_mitras_pks_mitra_id_foreign` (`pks_mitra_id` ASC) VISIBLE,
  INDEX `anggota_mitras_master_anggota_id_foreign` (`master_anggota_id` ASC) VISIBLE,
  CONSTRAINT `anggota_mitras_commitmentbackdate_id_foreign`
    FOREIGN KEY (`commitmentbackdate_id`)
    REFERENCES `lasimethris02`.`commitment_backdates` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `anggota_mitras_master_anggota_id_foreign`
    FOREIGN KEY (`master_anggota_id`)
    REFERENCES `lasimethris02`.`master_anggotas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `anggota_mitras_no_ijin_foreign`
    FOREIGN KEY (`no_ijin`)
    REFERENCES `lasimethris02`.`commitment_backdates` (`no_ijin`)
    ON DELETE CASCADE,
  CONSTRAINT `anggota_mitras_pks_mitra_id_foreign`
    FOREIGN KEY (`pks_mitra_id`)
    REFERENCES `lasimethris02`.`pks_mitras` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
